#!/usr/bin/env bash
# this script will config nginx to redirect to another website
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /usr/share/nginx/html/;
    index  index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html{
        root /usr/share/nginx/html/;
        internal;
    }
}" > /etc/nginx/sites-available/default
service nginx start
