#!/usr/bin/env bash
# this script will ping an ip passed to it as an command-line argument

if [ "$#" -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
else
	ping "$1" -c 5
fi
