#!/usr/bin/env bash
# This script will print Best School 10 times but in the 9th will print Best school and then hi
count="0"
while [ $count -ne 10 ]
do
	echo "Best School"
	((count++))
	if [ "$count" = 9 ]
	then
		echo "Hi"
	fi
done
