#!/usr/bin/env bash
# This script will print numbers from 1 to 20 but in 4 will print "bad luck from china" and in 9 "bad luck from japan" and in 17 "bad luck from italy"
count="1"
while [ $count -ne "21" ]
do
	echo "$count"
	case $count in
		"4")
			echo "bad luck from China"
		;;
		"9")
			echo "bad luck from Japan"
		;;
		"17")
			echo "bad luck from Italy"
	esac
	((count++))
done
