#!/usr/bin/env bash
#this script will print time for 12 hours and 59 minutes.

hours="0"

while [ $hours -ne "13" ]
do
	minutes="1"

	echo "Hour: $hours"

	while [ $minutes -ne "60" ]
	do
		echo "$minutes"
		((minutes++))
	done
	((hours++))
done
